proxies:
  - {
      "type": "vless",
      "name": "🇺🇸 vl-reality-MegaBox",
      "server": "104.224.153.17",
      "port": 14072,
      "uuid": "4af9492b-4bb0-4ad7-b0ea-b4967846e7f8",
      "tls": true,
      "flow": "xtls-rprx-vision",
      "client-fingerprint": "chrome",
      "skip-cert-verify": false,
      "reality-opts":
        {
          "public-key": "8XrLxEa0v1DIsykskNUIOYs4aOPuVcOkUgV6P9r_hH0",
          "short-id": "95fd6391",
        },
      "network": "tcp",
      "encryption": "none",
      "servername": "apple.com",
    }
  - {
      "type": "hysteria2",
      "name": "🇺🇸 hy2-MegaBox",
      "server": "104.224.153.17",
      "port": 28240,
      "password": "4af9492b-4bb0-4ad7-b0ea-b4967846e7f8",
      "sni": "www.bing.com",
      "skip-cert-verify": true,
      "tfo": false,
    }
  - {
      "type": "tuic",
      "name": "🇺🇸 tu5-MegaBox",
      "server": "104.224.153.17",
      "port": 24037,
      "password": "4af9492b-4bb0-4ad7-b0ea-b4967846e7f8",
      "uuid": "4af9492b-4bb0-4ad7-b0ea-b4967846e7f8",
      "congestion-controller": "bbr",
      "udp-relay-mode": "native",
      "alpn": ["h3"],
      "sni": "www.bing.com",
      "skip-cert-verify": true,
      "allowInsecure": "1",
      "version": 5,
    }
  - {
      "type": "anytls",
      "name": "🇺🇸 anytls-MegaBox",
      "server": "104.224.153.17",
      "port": 45214,
      "sni": "www.bing.com",
      "skip-cert-verify": true,
      "password": "4af9492b-4bb0-4ad7-b0ea-b4967846e7f8",
      "allowInsecure": "1",
    }
  - {
      "type": "vless",
      "name": "🇭🇰 vl-reality-ZhangYida",
      "server": "89.251.26.122",
      "port": 14807,
      "uuid": "dca013f3-2447-4434-b04c-42de6e49034f",
      "tls": true,
      "flow": "xtls-rprx-vision",
      "client-fingerprint": "chrome",
      "skip-cert-verify": false,
      "reality-opts":
        {
          "public-key": "cUq772-czdn7TD9qXEwCcduoZmBn5N8dQdCCoLC7cBM",
          "short-id": "7956a311",
        },
      "network": "tcp",
      "encryption": "none",
      "servername": "apple.com",
    }
  - {
      "type": "hysteria2",
      "name": "🇭🇰 hy2-ZhangYida",
      "server": "89.251.26.122",
      "port": 44973,
      "password": "dca013f3-2447-4434-b04c-42de6e49034f",
      "sni": "www.bing.com",
      "skip-cert-verify": true,
      "tfo": false,
    }
  - {
      "type": "tuic",
      "name": "🇭🇰 tu5-ZhangYida",
      "server": "89.251.26.122",
      "port": 58636,
      "password": "dca013f3-2447-4434-b04c-42de6e49034f",
      "uuid": "dca013f3-2447-4434-b04c-42de6e49034f",
      "congestion-controller": "bbr",
      "udp-relay-mode": "native",
      "alpn": ["h3"],
      "sni": "www.bing.com",
      "skip-cert-verify": true,
      "allowInsecure": "1",
      "version": 5,
    }
  - {
      "type": "anytls",
      "name": "🇭🇰 anytls-ZhangYida",
      "server": "89.251.26.122",
      "port": 27771,
      "sni": "www.bing.com",
      "skip-cert-verify": true,
      "password": "dca013f3-2447-4434-b04c-42de6e49034f",
      "allowInsecure": "1",
    }
  - {
      "type": "vless",
      "name": "🇭🇰 vl-reality-GreenCloudHK",
      "server": "96.9.229.232",
      "port": 59465,
      "uuid": "0c268d34-1811-48a6-ab46-7624109b8415",
      "tls": true,
      "flow": "xtls-rprx-vision",
      "client-fingerprint": "chrome",
      "skip-cert-verify": false,
      "reality-opts":
        {
          "public-key": "U4xuJE8tS4fHJL8IHHXacM4aZIzo2qNkTSK36MeweG8",
          "short-id": "e56206d6",
        },
      "network": "tcp",
      "encryption": "none",
      "servername": "apple.com",
    }
  - {
      "type": "hysteria2",
      "name": "🇭🇰 hy2-GreenCloudHK",
      "server": "96.9.229.232",
      "port": 37773,
      "password": "0c268d34-1811-48a6-ab46-7624109b8415",
      "sni": "www.bing.com",
      "skip-cert-verify": true,
      "tfo": false,
    }
  - {
      "type": "tuic",
      "name": "🇭🇰 tu5-GreenCloudHK",
      "server": "96.9.229.232",
      "port": 41788,
      "password": "0c268d34-1811-48a6-ab46-7624109b8415",
      "uuid": "0c268d34-1811-48a6-ab46-7624109b8415",
      "congestion-controller": "bbr",
      "udp-relay-mode": "native",
      "alpn": ["h3"],
      "sni": "www.bing.com",
      "skip-cert-verify": true,
      "allowInsecure": "1",
      "version": 5,
    }
  - {
      "type": "anytls",
      "name": "🇭🇰 anytls-GreenCloudHK",
      "server": "96.9.229.232",
      "port": 23189,
      "sni": "www.bing.com",
      "skip-cert-verify": true,
      "password": "0c268d34-1811-48a6-ab46-7624109b8415",
      "allowInsecure": "1",
    }
  - {
      "type": "vless",
      "name": "🇯🇵 vl-reality-googletokyo",
      "server": "34.146.36.142",
      "port": 46977,
      "uuid": "de65ead0-5426-403c-bd96-d02d24a0a017",
      "tls": true,
      "flow": "xtls-rprx-vision",
      "client-fingerprint": "chrome",
      "skip-cert-verify": false,
      "reality-opts":
        {
          "public-key": "dTqJFCg5ZsrheRjX8khRQY1QwlFXYDxeL0umZLy19mg",
          "short-id": "e33e786a",
        },
      "network": "tcp",
      "encryption": "none",
      "servername": "apple.com",
    }
  - {
      "type": "hysteria2",
      "name": "🇯🇵 hy2-googletokyo",
      "server": "34.146.36.142",
      "port": 59529,
      "password": "de65ead0-5426-403c-bd96-d02d24a0a017",
      "sni": "www.bing.com",
      "skip-cert-verify": true,
      "tfo": false,
    }
  - {
      "type": "tuic",
      "name": "🇯🇵 tu5-googletokyo",
      "server": "34.146.36.142",
      "port": 36092,
      "password": "de65ead0-5426-403c-bd96-d02d24a0a017",
      "uuid": "de65ead0-5426-403c-bd96-d02d24a0a017",
      "congestion-controller": "bbr",
      "udp-relay-mode": "native",
      "alpn": ["h3"],
      "sni": "www.bing.com",
      "skip-cert-verify": true,
      "allowInsecure": "1",
      "version": 5,
    }
  - {
      "type": "anytls",
      "name": "🇯🇵 anytls-googletokyo",
      "server": "34.146.36.142",
      "port": 53216,
      "sni": "www.bing.com",
      "skip-cert-verify": true,
      "password": "de65ead0-5426-403c-bd96-d02d24a0a017",
      "allowInsecure": "1",
    }
  - {
      "type": "vless",
      "name": "🇭🇰 vl-reality-googlehk",
      "server": "35.220.228.23",
      "port": 62311,
      "uuid": "7ca255ba-13ef-4740-84ac-10284e274f1a",
      "tls": true,
      "flow": "xtls-rprx-vision",
      "client-fingerprint": "chrome",
      "skip-cert-verify": false,
      "reality-opts":
        {
          "public-key": "m8NsYOLTmFKIdR4I3CQ4Mo9AA019F6X1Gfyck6Vr-hA",
          "short-id": "ef5fb93e",
        },
      "network": "tcp",
      "encryption": "none",
      "servername": "apple.com",
    }
  - {
      "type": "hysteria2",
      "name": "🇭🇰 hy2-googlehk",
      "server": "35.220.228.23",
      "port": 44859,
      "password": "7ca255ba-13ef-4740-84ac-10284e274f1a",
      "sni": "www.bing.com",
      "skip-cert-verify": true,
      "tfo": false,
    }
  - {
      "type": "tuic",
      "name": "🇭🇰 tu5-googlehk",
      "server": "35.220.228.23",
      "port": 12818,
      "password": "7ca255ba-13ef-4740-84ac-10284e274f1a",
      "uuid": "7ca255ba-13ef-4740-84ac-10284e274f1a",
      "congestion-controller": "bbr",
      "udp-relay-mode": "native",
      "alpn": ["h3"],
      "sni": "www.bing.com",
      "skip-cert-verify": true,
      "allowInsecure": "1",
      "version": 5,
    }
  - {
      "type": "anytls",
      "name": "🇭🇰 anytls-googlehk",
      "server": "35.220.228.23",
      "port": 47511,
      "sni": "www.bing.com",
      "skip-cert-verify": true,
      "password": "7ca255ba-13ef-4740-84ac-10284e274f1a",
      "allowInsecure": "1",
    }
  - {
      "type": "vless",
      "name": "🇧🇬 vl-reality-Alpha",
      "server": "82.118.235.185",
      "port": 36624,
      "uuid": "5dc5a841-57d1-49c8-b8a5-9d4eb8b0f0bc",
      "tls": true,
      "flow": "xtls-rprx-vision",
      "client-fingerprint": "chrome",
      "skip-cert-verify": false,
      "reality-opts":
        {
          "public-key": "jH0XFo5MR1A291-dIuJNAZNaLt9r10TnbwD_yneGEEA",
          "short-id": "d6d2441d",
        },
      "network": "tcp",
      "encryption": "none",
      "servername": "apple.com",
    }
  - {
      "type": "hysteria2",
      "name": "🇧🇬 hy2-Alpha",
      "server": "82.118.235.185",
      "port": 13879,
      "password": "5dc5a841-57d1-49c8-b8a5-9d4eb8b0f0bc",
      "sni": "www.bing.com",
      "skip-cert-verify": true,
      "tfo": false,
    }
  - {
      "type": "tuic",
      "name": "🇧🇬 tu5-Alpha",
      "server": "82.118.235.185",
      "port": 63169,
      "password": "5dc5a841-57d1-49c8-b8a5-9d4eb8b0f0bc",
      "uuid": "5dc5a841-57d1-49c8-b8a5-9d4eb8b0f0bc",
      "congestion-controller": "bbr",
      "udp-relay-mode": "native",
      "alpn": ["h3"],
      "sni": "www.bing.com",
      "skip-cert-verify": true,
      "allowInsecure": "1",
      "version": 5,
    }
  - {
      "type": "anytls",
      "name": "🇧🇬 anytls-Alpha",
      "server": "82.118.235.185",
      "port": 22915,
      "sni": "www.bing.com",
      "skip-cert-verify": true,
      "password": "5dc5a841-57d1-49c8-b8a5-9d4eb8b0f0bc",
      "allowInsecure": "1",
    }
